services:
  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    restart: always
    environment:
      - POSTGRES_DB=challenge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
  
 